      *================================================================*
      * Program: &PGM|                                                *
      * Date:    &WDATE|                                              *
      * Time:    &WTIME|                                              *
      * Table:   &TBL|                                                *
      * Generated by GENOWA Code Generation Tool                      *
      *================================================================*
       IDENTIFICATION DIVISION.
       PROGRAM-ID. &PGM|.
       AUTHOR. GENOWA.
       DATE-WRITTEN. &WDATE|.
      *----------------------------------------------------------------*
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-3090.
       OBJECT-COMPUTER. IBM-3090.
      *----------------------------------------------------------------*
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *----------------------------------------------------------------*
      * SQL Include Area
      *----------------------------------------------------------------*
           EXEC SQL INCLUDE SQLCA END-EXEC.
      *----------------------------------------------------------------*
      * Working Variables
      *----------------------------------------------------------------*
       01  WS-RETURN-CODE            PIC S9(9) COMP VALUE ZERO.
       01  WS-SQLCODE                PIC S9(9) COMP VALUE ZERO.
       01  WS-TABLE-NAME             PIC X(18) VALUE '&TBL|'.
      *----------------------------------------------------------------*
      * Host Variables for SQL
      *----------------------------------------------------------------*
       &WSVARS|
      *----------------------------------------------------------------*
       LINKAGE SECTION.
       01  DFHCOMMAREA.
           05 CA-FUNCTION            PIC X(4).
           05 CA-RETURN-CODE         PIC S9(4) COMP.
           05 CA-TABLE-DATA.
      &FULLKEY|
      *----------------------------------------------------------------*
       PROCEDURE DIVISION.
      *----------------------------------------------------------------*
       0000-MAIN.
           PERFORM 1000-INITIALIZE
           PERFORM 2000-PROCESS
           PERFORM 9000-TERMINATE
           GOBACK.
      *----------------------------------------------------------------*
       1000-INITIALIZE.
           MOVE ZEROS TO WS-RETURN-CODE
           MOVE ZEROS TO WS-SQLCODE.
      *----------------------------------------------------------------*
       2000-PROCESS.
           EVALUATE CA-FUNCTION
               WHEN 'READ'
                   PERFORM 3000-READ-TABLE
               WHEN 'WRIT'
                   PERFORM 4000-WRITE-TABLE
               WHEN OTHER
                   MOVE 99 TO CA-RETURN-CODE
           END-EVALUATE.
      *----------------------------------------------------------------*
       3000-READ-TABLE.
      * Set key values from linkage
       &SETKEY|
      *
      * Execute the SQL SELECT
           EXEC SQL
               SELECT &SQLC|
               INTO   &SQLF|
               FROM   &TBL|
               WHERE  &FULLKEY|
           END-EXEC
           MOVE SQLCODE TO WS-SQLCODE
           IF SQLCODE = 0
               MOVE 0 TO CA-RETURN-CODE
           ELSE
               MOVE 1 TO CA-RETURN-CODE
           END-IF.
      *----------------------------------------------------------------*
       4000-WRITE-TABLE.
      * Move host variables
       &MOVEHV2|
      *
      * Execute the SQL INSERT
           EXEC SQL
               INSERT INTO &TBL|
               (&SQLC|)
               VALUES (&SQLI|)
           END-EXEC
           MOVE SQLCODE TO WS-SQLCODE
           IF SQLCODE = 0
               MOVE 0 TO CA-RETURN-CODE
           ELSE
               MOVE 2 TO CA-RETURN-CODE
           END-IF.
      *----------------------------------------------------------------*
       9000-TERMINATE.
           CONTINUE.
      *----------------------------------------------------------------*
